var NewsGuardianConfig = {
    // FIXME: Don't forget to remove the test links ('subgenius', etc.)

    /**
     * Default list of highlighted domains
     * @type {string[]}
     */
    DOMAINS: [ 
		"thehardtimes.net", "rstreet.org", "express.co.uk", "breaking911.com", "usasupreme.com", "70news.wordpress.com",
		"northcrane.com",
        "onion.com", "theonion.com", "clickhole.com", "private-eye.co.uk", "newsbiscuit.com", "thespoof.com",
        "unconfirmedsources.com", "cap-news.com", "enduringvision.com", "derfmagazine.com", "newsmutiny.com",
        "p4rgaming.com", "thedailypixel.com", "dailycurrant.com", "borowitz-report", "callthecops.net",
        "empirenews.net", "empiresports.co", "freewoodpost.com", "mediafetcher.com", "globalassociatednews.com",
        "huzlers.com", "thelapine.ca", "lightlybraisedturnip.com", "mediamass.net", "nationalreport.net",
        "theracketreport.com", "weeklyworldnews.com", "worldnewsdailyreport.com", "scrappleface.com", "bongonews.com",
        "thepeoplescube.com", /*"utm_hp_ref=satire",*/ "newswatch28.com", "thenewsnerd.com", "dailymediabuzz.com",
        "demyx.com", "newslo.com", "shareonfb.com", "chronicle.su", "duffelblog.com", "duhprogressive.com",
        "stubhillnews.com", "nbc.com.co", "starwipe.com", "liberaldarkness.com", "politicalgarbagechute.com",
        "christwire.org", "civictribune.com", "creambmp.com", "dcgazette.com", "msnbc.website", "newsmutiny.com",
        "politicalears.com", "realnewsrightnow.com", "rilenews.com", "witscience.org", "gomerblog.com", "nahadaily.com",
        "rockcitytimes.com", "thedailymash.co.uk", "thedime.ca", "newswatch33.com", "cbsnews.com.co", "now8news.com",
        "syruptrap.ca", "reportquickly.com", "news.bfnn.co.uk", "article107news.com", "totalfratmove.com",
        "neomongolianewsnetwork.com", "onionstudios.com", "abcnews.com.co", "submediant.com", "russiainyourface.com",
        "satiratribune.com", "waterfordwhispersnews.com", "pointandclickbait.com", "thesciencepost.com",
        "empireherald.com", "bizstandardnews.com", "burrardstreetjournal.com",
        "infowars.com", "prisonplanet.com", "prisonplanet.tv", "in5d.com", "whatreallyhappened.com",
        "wanttoknow.info", "beforeitsnews.com", "cabaltimes.com", "rense.com", "crossroad.to", "alternet.org",
        "watch-unto-prayer.org", "madcowprod.com", "globalresearch.ca", ".rt.com", "presstv.ir", "barrychamish.com",
        "godlikeproductions.com", "stj911.org", "goroadachi.com", "henrymakow.com", "educate-yourself.org",
        "letsrollforums.com", "vigilantcitizen.com", "voltairenet.org", "larouchepub.com", "theblaze.com",
        "septemberclues.info", "thetruthseeker.co.uk", "mufon.com", "mufoncanada.com", "openminds.tv",
        "drudgereport.com", "naturalnews.com", "coasttocoastam.com", "davidicke.com", "activistpost.com",
        "stevequayle.com", "shtfplan.com", "thedailysheeple.com", "informationclearinghouse.info",
        "americanfreepress.net", "antiwar.com", "truthstreammedia.com", "thenewamerican.com", "tarpley.net",
        "911truth.org", "wnd.com", "propagandamatrix.com", "oathkeepers.org", "cryptogon.com", "alt-market.com",
        "legitgov.org", "whatdoesitmean.com", "ronpaulinstitute.org", "tvnewslies.org", "dprogram.net", "smoloko.com",
        "themindunleashed.org", "waykiwayki.com", "disclose.tv", /*"mirror.co.uk",*/ "dailystar.co.uk", /*"dailymail.co.uk",*/
        "thesun.co.uk", "mercola.com", "agoracosmopolitan.com", "cryptozoologynews.com", "newshounds.us",
        "topekasnews.com", "pravda.ru", "eutimes.net", "examiner.com", "theepochtimes.com", "yournewswire.com",
        "worldtruth.tv", "wakeup-world.com", "ewao.com", "ufointernationalproject.com", "spiritlibrary.com",
        "theinsider.org", "collective-evolution.com", "ufosonline.blogspot.com.br", "ufocasebook.com",
        "exopolitics.org", "doctoroz.com", "drphil.com", "conspiracytheorist.com.au", "ijreview.com",
        "thefreethoughtproject.com", "21stcenturywire.com", "800WhistleBlower.com", "therundownlive.com",
        "consciouslifenews.com", "conspiracywire.com", "countdowntozerotime.com", "counterpsyops.com",
        "dailybuzzlive.com", "dcclothesline.com", "elitereaders.com", "sputniknews.com", "federalistpress.com",
        "fromthetrenchesworldreport.com", "geoengineeringwatch.org", "govtslaves.info", "gulagbound.com",
        "hangthebankers.com", "healthimpactnews.com", "humansarefree.com", "intellihub.com", "lewrockwell.com",
        "libertynews.com", "livefreelivenatural.com", "newswire-24.com", "nodisinfo.com", "notallowedto.com",
        "nowtheendbegins.com", "politicalblindspot.com", "rawforbeauty.com", "realfarmacy.com", "redflagnews.com",
        "responsibletechnology.org", "secretsofthefed.com", "thecommonsenseshow.com", "thecontroversialfiles.net",
        "thelastgreatstand.com", "therightplanet.com", "theuspatriot.com", "topinfopost.com", "truthandaction.org",
        "truthbroadcastnetwork.com", "usahitman.com", "veteranstoday.com", "westernjournalism.com", "crazed.com",
        "whydontyoutrythis.com", "healthyandnaturallife.com", "dailycaller.com", "consciouslyenlightened.com",
        "mrconservative.com", "forbes.com", "thesleuthjournal.com", "investmentresearchdynamics.com",
        "tomatobubble.com", "bunkerville.wordpress.com", "theunhivedmind.com", "theantimedia.org",
        "truthcdm.com", "mycatbirdseat.com", "rt.com", "truth-out.org", "whatsupic.com", "whatsupic.com",
        "911blogger.com", "zerohedge.com", "thefederalist.com", "blacklistednews.com",
        "thefederalist-gary.blogspot.com", "rinf.com", "vdare.com", "christopherketcham.com",
        "iceagenow.info", "hiduth.com", "whowhatwhy.org", "zerocensorship.com", "inquisitr.com",
        "topsecretwriters.com", "alternativenewsproject.org", "unreddit.com", "independenceday.pro",
        "blog.world-mysteries.com", "tradyouth.org", "collectivelyconscious.net",
        "americablog.com", "republicreport.org", "opednews.com", "therightscoop.com", "nationaltribune.com",
        "thegoodsurvivalist.com", "anonhq.com", "indian-skeptic.org", "indiansceptic.in",
        "philosophers-stone.co.uk", "kendoc911.files.wordpress.com", "freerepublic.com", "sott.net",
        "wattsupwiththat.com", "subvertednation.net", "jewishcrimenetworkdid911.blogspot.com.au",
        "seeker401.wordpress.com", "revelation13.net", "gotnews.com", "reason.com", "thegatewaypundit.com",
        "tvoinews.com", "rightwingwatch.org", "boilingfrogspost.com", "allnewspipeline.com", "greenlifes.net",
        "therealnews.com", "bigamericannews.com", "jewsnews.co.il", "foodbabe.com", "donotlink.com",
        "americannews.com", "healthiswealthofheart.com", "rightwingnews.com", "clashdaily.com",
        "ddsdtv.blogspot.com", "rebeldietitian.us", "prevention.com", "mindbodygreen.com", "thespiritscience.net",
        "enenews.com", "returnofkings.com", "rooshv.com", "fixedearth.com", "freerepublic.com", "angrywhitedude.com",
        "eagleforum.org", "afa.net", "metapedia.org", "rexresearch.com", "whitehonor.com", "conservapedia.com",
        "stormfront.org", "godvine.com", "patriotaction.net", "newsbusters.org", "greenmedinfo.com",
        "conservativetribune.com", "southideas.net", "shockingtimes.co.uk", "gmmuk.com", "truthalerts.com",
        "corproject.com", "superstation95.com", "healthy-holistic-living.com", "zonnews.com", "real-people-stories.pw"

        // If Drudge Report actually hosted its own original content, rest assured, a link to the site would go here.
    ]
};
